-- Insert sample posts using gen_random_uuid()
INSERT INTO public.posts (title, content, post_type, author_id, community_id, tags, upvotes, comment_count, is_pinned) VALUES
('Best Indian restaurants in Bay Area?', 'Hey everyone! I''m new to the Bay Area and looking for authentic Indian restaurants. Any recommendations for good South Indian food? Especially looking for places with great dosas and sambar!', 'question', '11111111-1111-1111-1111-111111111111', (SELECT id FROM communities WHERE name = 'San Francisco Bay Area Indian Community'), ARRAY['food', 'restaurants', 'recommendations'], 23, 8, false),
('Tech Career Growth Discussion', 'Starting a thread about career growth in tech. What are the best strategies for moving from individual contributor to management roles? Would love to hear experiences from fellow Indian professionals.', 'discussion', '22222222-2222-2222-2222-222222222222', (SELECT id FROM communities WHERE name = 'Seattle Indian Professionals'), ARRAY['career', 'tech', 'management'], 45, 12, true),
('Free Health Checkup Camp - This Weekend', 'Our community is organizing a free health checkup camp this weekend at the community center. We''ll have doctors volunteering for basic screenings. Please spread the word!', 'announcement', '33333333-3333-3333-3333-333333333333', (SELECT id FROM communities WHERE name = 'Austin Indian Association'), ARRAY['health', 'community', 'volunteer'], 67, 5, true),
('Investment Guide for H1B Holders', 'Comprehensive guide on investment options available for H1B visa holders. Covering 401k, IRA, taxable accounts, and tips for international investing. Let me know if you have questions!', 'resource', '44444444-4444-4444-4444-444444444444', (SELECT id FROM communities WHERE name = 'New York Indian Chamber of Commerce'), ARRAY['finance', 'investing', 'visa', 'guide'], 89, 15, false),
('Diwali Celebration Planning', 'Who''s excited for our upcoming Diwali celebration? We''re still looking for volunteers to help with decorations and food coordination. Also, if anyone knows good Bollywood DJs, please comment below!', 'discussion', '55555555-5555-5555-5555-555555555555', (SELECT id FROM communities WHERE name = 'Chicago Desi Network'), ARRAY['diwali', 'celebration', 'volunteers'], 34, 18, false);

-- Insert sample marketplace listings
INSERT INTO public.marketplace (title, description, category, price, is_negotiable, seller_id, community_id, location, contact_info, status, images) VALUES
('Indian Pressure Cooker Set', 'Brand new Hawkins pressure cooker set with 3L and 5L cookers. Perfect for Indian cooking. Never used, received as gift.', 'goods', 89.99, true, '11111111-1111-1111-1111-111111111111', (SELECT id FROM communities WHERE name = 'San Francisco Bay Area Indian Community'), 'San Francisco, CA', '{"phone": "(415) 555-0101", "email": "priya.sharma@email.com"}', 'active', ARRAY[]::text[]),
('Software Consulting Services', 'Offering web development and mobile app consulting services. Specializing in React, Node.js, and React Native. Competitive rates for community members.', 'services', 75.00, true, '22222222-2222-2222-2222-222222222222', (SELECT id FROM communities WHERE name = 'Seattle Indian Professionals'), 'Seattle, WA', '{"phone": "(206) 555-0202", "email": "rajesh.patel@email.com"}', 'active', ARRAY[]::text[]),
('Roommate Wanted - 2BR Apartment', 'Looking for a roommate to share a beautiful 2-bedroom apartment near downtown Austin. Indian vegetarian household, no smoking. Rent $800/month including utilities.', 'housing', 800.00, false, '33333333-3333-3333-3333-333333333333', (SELECT id FROM communities WHERE name = 'Austin Indian Association'), 'Austin, TX', '{"phone": "(512) 555-0303", "email": "anita.krishnan@email.com"}', 'active', ARRAY[]::text[]),
('Financial Analyst Position', 'Our investment firm is hiring a Financial Analyst. 3+ years experience required. Excellent benefits and growth opportunities. Indian candidates encouraged to apply.', 'jobs', 85000.00, false, '44444444-4444-4444-4444-444444444444', (SELECT id FROM communities WHERE name = 'New York Indian Chamber of Commerce'), 'New York, NY', '{"email": "careers@mehtafinancial.com", "website": "https://mehtafinancial.com/careers"}', 'active', ARRAY[]::text[]),
('Indian Classical Music Lessons', 'Experienced classical vocalist offering online and in-person music lessons. Beginner to advanced levels welcome. First lesson free for community members!', 'services', 50.00, true, '55555555-5555-5555-5555-555555555555', (SELECT id FROM communities WHERE name = 'Chicago Desi Network'), 'Chicago, IL', '{"phone": "(312) 555-0505", "email": "music@bollywooddance.com"}', 'active', ARRAY[]::text[]);

-- Insert sample resources
INSERT INTO public.resources (title, description, content, category, author_id, community_id, external_url, helpful_count, is_featured, tags) VALUES
('H1B to Green Card Timeline Guide', 'Comprehensive guide covering the entire process from H1B to permanent residency', 'This guide covers: PERM process timeline, I-140 filing, priority dates, adjustment of status, and common pitfalls to avoid. Updated for 2024 immigration policies.', 'Immigration', '44444444-4444-4444-4444-444444444444', (SELECT id FROM communities WHERE name = 'New York Indian Chamber of Commerce'), 'https://example.com/h1b-guide', 156, true, ARRAY['immigration', 'h1b', 'green card', 'visa']),
('Indian Grocery Shopping Guide - Bay Area', 'Complete list of Indian grocery stores with specialties and price comparisons', 'Detailed reviews of 20+ Indian grocery stores across Bay Area including Fremont, Sunnyvale, and South Bay. Includes specialty items availability and price ranges.', 'Lifestyle', '11111111-1111-1111-1111-111111111111', (SELECT id FROM communities WHERE name = 'San Francisco Bay Area Indian Community'), null, 89, false, ARRAY['grocery', 'shopping', 'bay area', 'food']),
('Ayurvedic Home Remedies for Common Ailments', 'Traditional Indian home remedies backed by modern research', 'Collection of time-tested Ayurvedic remedies for cold, flu, digestive issues, and stress. Includes preparation methods and scientific backing where available.', 'Health', '33333333-3333-3333-3333-333333333333', (SELECT id FROM communities WHERE name = 'Austin Indian Association'), 'https://example.com/ayurveda-guide', 234, true, ARRAY['ayurveda', 'health', 'home remedies', 'wellness']),
('Tech Interview Preparation for Indian Students', 'Comprehensive guide for acing tech interviews at top companies', 'Covers data structures, algorithms, system design, and behavioral questions. Includes cultural considerations and communication tips for international candidates.', 'Career', '22222222-2222-2222-2222-222222222222', (SELECT id FROM communities WHERE name = 'Seattle Indian Professionals'), 'https://example.com/tech-interview-guide', 312, true, ARRAY['tech', 'interview', 'career', 'coding']),
('Planning Indian Festivals in America', 'Guide to organizing traditional festivals while adapting to American settings', 'Tips for organizing Diwali, Holi, Navratri, and other festivals. Includes vendor recommendations, decoration ideas, and food planning for large groups.', 'Culture', '55555555-5555-5555-5555-555555555555', (SELECT id FROM communities WHERE name = 'Chicago Desi Network'), null, 178, false, ARRAY['festivals', 'culture', 'planning', 'events']);

-- Insert sample mentorships
INSERT INTO public.mentorships (mentor_id, mentee_id, focus_areas, message, status) VALUES
('44444444-4444-4444-4444-444444444444', '11111111-1111-1111-1111-111111111111', ARRAY['Career Transition', 'Finance', 'Investment'], 'Hi Vikram, I''m a software engineer looking to transition into fintech. Would love to learn about the finance industry from your perspective.', 'approved'),
('33333333-3333-3333-3333-333333333333', '55555555-5555-5555-5555-555555555555', ARRAY['Healthcare Marketing', 'Work-Life Balance'], 'Hello Dr. Krishnan, I''m in marketing but interested in healthcare sector. Could use guidance on industry transition and maintaining work-life balance.', 'pending'),
('22222222-2222-2222-2222-222222222222', '66666666-6666-6666-6666-666666666666', ARRAY['Product Management', 'Startup Strategy'], 'Hi Rajesh, I''m building a fintech startup and would value your product management expertise. Looking for guidance on product strategy and user research.', 'approved');