-- Insert sample profiles
INSERT INTO public.profiles (id, email, first_name, last_name, bio, profession, community_id, skills, interests, hometown_india, languages, linkedin_url, avatar_url, experience_years, is_verified) VALUES
('11111111-1111-1111-1111-111111111111', 'priya.sharma@email.com', 'Priya', 'Sharma', 'Software engineer with passion for building innovative solutions', 'Software Engineer', (SELECT id FROM communities WHERE name = 'San Francisco Bay Area Indian Community'), ARRAY['JavaScript', 'React', 'Node.js', 'Python'], ARRAY['Technology', 'Classical Music', 'Cooking', 'Hiking'], 'Mumbai', ARRAY['Hindi', 'English', 'Marathi'], 'https://linkedin.com/in/priyasharma', null, 5, true),
('22222222-2222-2222-2222-222222222222', 'rajesh.patel@email.com', 'Rajesh', 'Patel', 'Product manager helping startups scale and grow', 'Product Manager', (SELECT id FROM communities WHERE name = 'Seattle Indian Professionals'), ARRAY['Product Strategy', 'Data Analysis', 'Agile', 'Leadership'], ARRAY['Business', 'Cricket', 'Travel', 'Photography'], 'Ahmedabad', ARRAY['Hindi', 'English', 'Gujarati'], 'https://linkedin.com/in/rajeshpatel', null, 8, true),
('33333333-3333-3333-3333-333333333333', 'anita.krishnan@email.com', 'Anita', 'Krishnan', 'Healthcare professional dedicated to community wellness', 'Physician', (SELECT id FROM communities WHERE name = 'Austin Indian Association'), ARRAY['Internal Medicine', 'Public Health', 'Research'], ARRAY['Healthcare', 'Yoga', 'Volunteer Work', 'Reading'], 'Chennai', ARRAY['Tamil', 'English', 'Hindi'], null, null, 12, true),
('44444444-4444-4444-4444-444444444444', 'vikram.mehta@email.com', 'Vikram', 'Mehta', 'Finance professional with expertise in investment banking', 'Investment Banker', (SELECT id FROM communities WHERE name = 'New York Indian Chamber of Commerce'), ARRAY['Financial Analysis', 'Investment Strategy', 'Risk Management'], ARRAY['Finance', 'Tennis', 'Wine Tasting', 'Theater'], 'Delhi', ARRAY['Hindi', 'English', 'Punjabi'], 'https://linkedin.com/in/vikrammehta', null, 10, false),
('55555555-5555-5555-5555-555555555555', 'meera.shah@email.com', 'Meera', 'Shah', 'Marketing director passionate about brand storytelling', 'Marketing Director', (SELECT id FROM communities WHERE name = 'Chicago Desi Network'), ARRAY['Digital Marketing', 'Brand Strategy', 'Content Creation'], ARRAY['Marketing', 'Dancing', 'Art', 'Food'], 'Pune', ARRAY['Hindi', 'English', 'Marathi'], null, null, 7, false),
('66666666-6666-6666-6666-666666666666', 'arjun.reddy@email.com', 'Arjun', 'Reddy', 'Entrepreneur building the next generation of fintech solutions', 'Entrepreneur', (SELECT id FROM communities WHERE name = 'Boston Indian Professionals'), ARRAY['Entrepreneurship', 'Fintech', 'Machine Learning', 'Leadership'], ARRAY['Startups', 'Basketball', 'Podcasts', 'Meditation'], 'Hyderabad', ARRAY['Telugu', 'English', 'Hindi'], 'https://linkedin.com/in/arjunreddy', null, 6, true);

-- Insert sample businesses
INSERT INTO public.businesses (id, name, description, category, address, city, state, phone, email, website, rating, review_count, is_featured, owner_id, community_id) VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Spice Garden Indian Cuisine', 'Authentic Indian restaurant serving traditional dishes from across India', 'restaurant', '123 Main Street', 'San Francisco', 'CA', '(415) 555-0101', 'info@spicegarden.com', 'https://spicegarden.com', 4.5, 287, true, '11111111-1111-1111-1111-111111111111', (SELECT id FROM communities WHERE name = 'San Francisco Bay Area Indian Community')),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Desi Grocery Mart', 'Your one-stop shop for Indian groceries, spices, and specialty items', 'grocery', '456 Oak Avenue', 'Seattle', 'WA', '(206) 555-0202', 'contact@desigrocery.com', 'https://desigrocery.com', 4.2, 156, false, '22222222-2222-2222-2222-222222222222', (SELECT id FROM communities WHERE name = 'Seattle Indian Professionals')),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 'Ayurveda Wellness Center', 'Holistic healthcare combining modern medicine with ancient Ayurvedic practices', 'healthcare', '789 Wellness Way', 'Austin', 'TX', '(512) 555-0303', 'hello@ayurvedacenter.com', 'https://ayurvedacenter.com', 4.8, 94, true, '33333333-3333-3333-3333-333333333333', (SELECT id FROM communities WHERE name = 'Austin Indian Association')),
('dddddddd-dddd-dddd-dddd-dddddddddddd', 'Mehta Financial Advisory', 'Comprehensive financial planning and investment services', 'finance', '321 Wall Street', 'New York', 'NY', '(212) 555-0404', 'info@mehtafinancial.com', 'https://mehtafinancial.com', 4.6, 73, false, '44444444-4444-4444-4444-444444444444', (SELECT id FROM communities WHERE name = 'New York Indian Chamber of Commerce')),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'Bollywood Dance Academy', 'Learn traditional and modern Indian dance forms', 'education', '654 Dance Street', 'Chicago', 'IL', '(312) 555-0505', 'classes@bollywooddance.com', 'https://bollywooddance.com', 4.9, 128, true, '55555555-5555-5555-5555-555555555555', (SELECT id FROM communities WHERE name = 'Chicago Desi Network'));